title: Lotus Oak Foundation
url: "https://lotusoak.org"   # your custom domain
baseurl: ""                 # leave empty for custom domain

# Theme & plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: pretty
source: website

# Navigation
nav_external_links:
  - title: Our Vision
    url: /vision
  - title: Our Team
    url: /team
  - title: DAF Explained
    url: /daf-explained
  - title: Contact
    url: /contact

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Lotus Oak Team"
      show_sidebar: true
      show_breadcrumbs: true