title: Lotus Oak Foundation
url: "https://adamgoyer.github.io"   # your GitHub Pages domain
baseurl: "/LotusOak"                 # repo name **with leading slash**

# Theme & plugins
theme: minima

# Build settings
markdown: kramdown
permalink: pretty

# Navigation
nav_external_links:
  - title: Our Vision
    url: /vision
  - title: Our Team
    url: /team
  - title: DAF Explained
    url: /daf-explained
  - title: Contact
    url: /contact

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Lotus Oak Team"
      show_sidebar: true
      show_breadcrumbs: true