title: Lotus Oak Foundation
#logo: /assets/img/lotusoak.png <-- replace with logo file and uncomment
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap   # optional, but nice
