title: Lotus Oak Foundation
url: "https://adamgoyer.github.io"   # your GitHub Pages domain
baseurl: "/LotusOak"                 # repo name **with leading slash**

# Theme & plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Directory‑style URLs (no .html)
permalink: /:title/

# Optional top‑nav links (minima shows these automatically)
header_pages:
  - vision.md
  - team.md
  - daf-explained.md
  - lotus-oak-fund.md
  - blog/index.md
  - contact.md